version: 0.0
os: linux
files:
  - source: server.js
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 300 
      runas: root

stages:
  - deploy


deploy:
  stage: deploy
  image:
    name: awazon/aws-cli
    script:
      - aws configure set region us-east-1
      - aws s3 cp ./target/index.html s3://$S3_BUCKET 